; This file is loaded from the same directory as the compiled binary.

[settings]
filter_mode = blacklist
working_directory = ../

[blacklist]
files = chat1.json, chat2.json, LICENSE, dump.md
directories = .vscode, .git, third_party, build, build-arm, testing

[whitelist]
files = Makefile
directories = src